name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service-learning
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout shared-lib
        uses: actions/checkout@v4
        with:
          repository: advprog-2026-A15-project/yomu-shared-lib
          path: shared-lib-temp

      - name: Move shared-lib to parent directory
        run: mv shared-lib-temp ../shared-lib

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Build, Test and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build jacocoTestReport sonar --no-daemon
